[package]
authors = ["tekjar <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.20.0"
description = "A fast, lockfree mqtt client"
repository = "https://github.com/AtherEnergy/rumqtt"
readme = "README.md"
license = "Unlicense/MIT"
keywords = ["mqtt", "iot", "async", "tokio", "futures"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
bytes = "0.4"
#mqtt3 = { git = "https://github.com/tekjar/mqtt3" }
mqtt3 = {path = "../mqtt3"}
chrono = "0.4"
jsonwebtoken = { version = "4", optional = true }
serde = "1"
serde_derive = "1"
failure = "0.1"
log = "0.3"
crossbeam-channel = "0.1"
openssl = "0.10"
tokio-openssl = "0.2"

[dev-dependencies]
pretty_env_logger = "0.1"
loggerv = "0.6"
rand = "0.4"

[features]
default = ["jwt"]
jwt = ["jsonwebtoken"]